version: '3.8'

services:
    server:
        image: elkornacio/pg_auto_embeddings:latest
        environment:
            - PG_HOST=localhost
            - PG_PORT=5432
            - PG_USERNAME=root_user
            - PG_PASSWORD=root_pass
            - DATABASE_SYNC=true
            - SERVER_HOST=localhost
            - SERVER_PORT=3000
            - SELF_URL=http://localhost:3000
        ports:
            - 5432:5432
